### ISSUE TITLE
Working for android?

### ISSUE THREAD

**Issue by dansignia** [ingageco/capacitor-music-controls-plugin-for-capacitor-2#1]
Hi,

Did you manage to get this working for android in the end?

I have tried installing your plugin via NPM and have imported it but unable to get it to work.

Other than installing it via the NPM package you created and importing it into an angular page, how are you executing the plugin?

**Comment by ingageco** [comment]
hey @dansignia - yes, it's working. I can't say that 100% of the features are working but i was able to duplicate all of the same functionality from the Cordova plugin. The only problem i have right now is getting the cover image to show for iOS. I need to update the readme with the implementation that i'm using so you have an example - will do asap.

**Comment by ingageco** [comment]
At the top of your file import Plugins and this package

`import { Plugins } from '@capacitor/core';
import { CapacitorMusicControls } from 'capacitor-music-controls-plugin';`

Creating the controls: 

`const { CapacitorMusicControls } = Plugins;

// create your options - exact same as Cordova Music Controls
var options = {}

// create the controls
CapacitorMusicControls.create(options);

// listen for events and pass them to your handler function
CapacitorMusicControls.addListener('controlsNotification', (info: any) => {
			console.log('controlsNotification was fired');
			console.log(info);
			self.handleControlsEvent(info);
});			
		 
 		 
// update whether the music is playing true/false
		CapacitorMusicControls.updateIsPlaying({isPlaying: true}).catch(function(error){
			console.log("error reported:");
			console.log(error);
		});


// example handler

handleControlsEvent(action){

		console.log("hello from handleControlsEvent")
		const message = action.message;

		console.log("message: " + message)

		switch(message) {
			case 'music-controls-next':
				// next
				break;
			case 'music-controls-previous':
				// previous
				break;
			case 'music-controls-pause':

				// paused
				break;
			case 'music-controls-play':
				// resumed
				break;
			case 'music-controls-destroy':
				// controls were destroyed
				break;

			// External controls (iOS only)
			case 'music-controls-toggle-play-pause' :
				// do something

				break;
			case 'music-controls-seek-to':
				// catch seeking, example shown
                                const { CapacitorMusicControls } = Plugins;

				const seekToInSeconds = action.position;


				CapacitorMusicControls.updateElapsed({
					elapsed: this.playerPosition,
					isPlaying: true
				});
				// Do something
				break;
			case 'music-controls-skip-forward':
				// Do something
				break;
			case 'music-controls-skip-backward':
				// Do something
				break;

			// Headset events (Android only)
			// All media button events are listed below
			case 'music-controls-media-button' :
				// Do something
				break;
			case 'music-controls-headset-unplugged':
				// Do something
				break;
			case 'music-controls-headset-plugged':
				// Do something
				break;
			default:
				break;
		}
	}



`

**Comment by ingageco** [comment]
Sorry i'm terrible at formatting in these comments.

**Comment by ingageco** [comment]
@dansignia One more thing - it's possible that i haven't committed all of my changes for Android. I will do make sure this repo and NPM have the most recent version this week.

**Comment by dansignia** [comment]
Hi ingageco,

Thanks for the update.

For some reason CapacitorMusicControls does not exist as a property within Capacitor.Plugins. It doesn't look like it's listed in the pluginRegistry or has even been registered as a Capacitor Plugin.

Rather strange. 

To install your forked version, i just executed:
`npm i capacitor-music-controls-plugin`

Then executed:
`npx cap sync`

I am using Angular 8 however, and your usage of the plugin does look different as with the Cordova version you would import is as a provider and inject it through the constructor function.

I will keep digging around until something works.

Will let you know if something works :)

Thanks anyway 👍

**Comment by ingageco** [comment]
@dansignia I have noticed that I have to interact differently with this compared to the way other Capacitor plugins work. IT's a work in progress, but your experience is most likely due to the repo not being updated. 

To interface with Capacitor, i followed the official Capacitor documentation on both ends, with extran help from Josh Morony's tutorials on creating Capacitor plugins. 

Ill comment here again when i update the repo and know for sure that it's the most recent, working version that i have.

**Comment by dansignia** [comment]
Thanks for the update.

I was blind and forgot to do the following:

Within android studio in the applications MainActivity.java i had to add:

`import com.ingageco.capacitormusiccontrols.CapacitorMusicControls;`

and this inside the init method:

`add(CapacitorMusicControls.class);`

Seems to be working now.

Thanks for your help.

**Comment by ingageco** [comment]
The same caught me at first. I submitted a note to Capacitor that should be clarified in their docs (which they did).  I will have a readme with instructions for this plugin in the next couple of weeks. 

I lost some of the work that i had on this plugin initially, and now I'm working through making sure all of the features are re-implemented. Once i do that, i'll push the update as 1.0 and add the readme.

**Comment by tobika** [comment]
thanks for your work @ingageco 
I also moved my project from cordova to capacitor, did you more or less copy the code from the cordova plugin? I'm still using the cordova plugin with capacitor, I only use android and in this case the plugin works fine but will hopefully exchange it soon with yours :)

**Comment by Ekaanth** [comment]
> Thanks for the update.
> 
> I was blind and forgot to do the following:
> 
> Within android studio in the applications MainActivity.java i had to add:
> 
> `import com.ingageco.capacitormusiccontrols.CapacitorMusicControls;`
> 
> and this inside the init method:
> 
> `add(CapacitorMusicControls.class);`
> 
> Seems to be working now.
> 
> Thanks for your help.

Hi, I did follow this but when i run the app im getting
> E/Capacitor: Unable to execute plugin method
    com.getcapacitor.PluginInvocationException: Unable to invoke method create on plugin com.ingageco.capacitormusiccontrols.CapacitorMusicControls

as error any ideal how to resolve this issue.

Thankyou.
