### ISSUE TITLE
change the background and text color according to the image

### ISSUE THREAD

**Issue by rcasunshare** [ingageco/capacitor-music-controls-plugin-for-capacitor-2#17]
This plugin allows you to change the background and text color of the notification according to the image of the song that is displayed?
To look like this example?  

![50876941-94732480-13f5-11e9-8002-daa77ff85c3a](https://user-images.githubusercontent.com/12421510/93732015-f2ce3f80-fba5-11ea-89d9-768d2ac333ec.png)

**Comment by ingageco** [comment]
I'm not sure about that - i believe the color is dictated by the image - at least that's what i've seen.
