### ISSUE TITLE
Destroy function not complete?

### ISSUE THREAD

**Issue by gbeulque** [ingageco/capacitor-music-controls-plugin-for-capacitor-2#2]
Hi,

I was wondering if it could be that the destroy function doesn't completely destroy the music controls? It disappears, but it still fires events when pressing on of the buttons on a new music control box.

My scenario:

Every time I start another song it create a new CapacitorMusicControls with the options / track info of the current track. I do CapacitorMusicControls.destroy() to delete the existing notification box from the previous track.

I have added the event listener to CapacitorMusicControls like this: 
```
CapacitorMusicControls.addListener('controlsNotification', (info: any) => {
				this.handleControlsEvent(info);
			});
```

What I notice in my logging is that for every CapacitorMusicControls I have created (thus for each track I have ever started), they fire an event on clicking one of the buttons.

Results from that:

-I can only pause the music on uneven tracks: first track works, pause is only fired once, second track can't be paused as the pause event is fired twice, third track works again as the pause event is fired three times.

If this is not a bug, than how can I make sure events are only fired once?

```
native CapacitorMusicControls.updateIsPlaying (#4322573)
capacitor-runtime.js:410 result CapacitorMusicControls.addListener (#114873014)
capacitor-runtime.js:410 result CapacitorMusicControls.addListener (#4322569)
capacitor-runtime.js:410 result CapacitorMusicControls.addListener (#114873014)
capacitor-runtime.js:410 result CapacitorMusicControls.addListener (#4322569)
capacitor-runtime.js:410 result CapacitorMusicControls.addListener (#114873014)
capacitor-runtime.js:410 result CapacitorMusicControls.addListener (#4322569)
capacitor-runtime.js:410 result CapacitorMusicControls.updateIsPlaying (#4322573)
capacitor-runtime.js:410 result CapacitorMusicControls.addListener (#114873014)
capacitor-runtime.js:410 result CapacitorMusicControls.addListener (#4322569)
capacitor-runtime.js:386 native CapacitorMusicControls.updateIsPlaying (#4322574)
capacitor-runtime.js:410 result CapacitorMusicControls.addListener (#114873014)
capacitor-runtime.js:410 result CapacitorMusicControls.addListener (#4322569)
capacitor-runtime.js:410 result CapacitorMusicControls.addListener (#114873014)
capacitor-runtime.js:410 result CapacitorMusicControls.addListener (#4322569)
capacitor-runtime.js:410 result CapacitorMusicControls.addListener (#114873014)
capacitor-runtime.js:410 result CapacitorMusicControls.addListener (#4322569)
capacitor-runtime.js:410 result CapacitorMusicControls.updateIsPlaying (#4322574)
capacitor-runtime.js:410 result CapacitorMusicControls.addListener (#114873014)
capacitor-runtime.js:410 result CapacitorMusicControls.addListener (#4322569)
```

**Comment by ingageco** [comment]
I do think this is a bug. It sounds like destroy is not unregistering the listeners.

**Comment by ingageco** [comment]
Are you using this only on iOS or both iOS/Android at the moment?

**Comment by gbeulque** [comment]
Waw, thanks for the fast reply!! And also thanks a lot for making this plugin compatible with Capacitor!!

I am currently only testing on Android. Eventually will have to work on iOS as well, but I don't have an iPhone available to test atm.

Thanks!!

**Comment by ingageco** [comment]
OK - android is in need of a test/update. I originally had everything working on both ios/android and i lost some work unfortunately. So i have been combing back through iOS to get it to 100% completion and i haven't made it back to Android just yet. Expect an update in the next couple of weeks that should round out the rest of the Android functionality.

**Comment by gbeulque** [comment]
I have added these lines to the destroy function, and that seems to fix it:

`final Context context=getActivity().getApplicationContext();
		context.unregisterReceiver(mMessageReceiver);`

**Comment by trabdin** [comment]
I seem to have this problem with iOS. If I destroy and then create again, I get two events for each action. I thought maybe it had something to do with addObserver and removeObserver having different names?

`NotificationCenter.default.addObserver(self, selector: #selector(self.handleMusicControlsNotification(_:)), name: NSNotification.Name(rawValue: "musicControlsEventNotification"), object: nil)`

`NotificationCenter.default.removeObserver(self, name: NSNotification.Name(rawValue: "receivedEvent"), object: nil)`

But I tried changing "receivedEvent" to "musicControlsEventNotification" but it still seems to behave the same way...

**Comment by ingageco** [comment]
@trabdin @gbeulque good find. Im trying to make my way back to updating this plugin in the next couple of weeks as my schedule shifts to a few app projects that need it. I'll try this and update the repo with any progress i make on iOS/Android.

**Comment by ingageco** [comment]
PRs welcome as well if you've made any progress.

**Comment by ingageco** [comment]
@trabdin I see you made a lot of changes to the iOS implementation on your fork. Do you have everything working? Your implementation looks much cleaner.

**Comment by B1Z1** [comment]
Is it solved?
