### ISSUE TITLE
Pleas Update

### ISSUE THREAD

**Issue by tnhgm** [ingageco/capacitor-music-controls-plugin-for-capacitor-2#24]
please update this plugin for capacitor 3 and 4
i can't find any plugin that work with new capacitor
i need to it very much

**Comment by ingageco** [comment]
Sorry, this plugin is currently only for Capacitor 2

**Comment by ingageco** [comment]
https://github.com/ingageco/capacitor-music-controls-plugin-v3 (WIP)
