### ISSUE TITLE
how to use in my project IONIC 4?

### ISSUE THREAD

**Issue by julianokunha** [ingageco/capacitor-music-controls-plugin-for-capacitor-2#3]

**Comment by lbesiche** [comment]
after you install the plugin go to your MainActivity.java

import this path:
import com.ingageco.capacitormusiccontrols.CapacitorMusicControls;

add class inside bridge activity:
add(CapacitorMusicControls.class);

finally run 
npx cap sync android

https://github.com/ingageco/capacitor-music-controls-plugin/issues/1#issuecomment-552383133
