### ISSUE TITLE
TypeScript: Unexpected token. A constructor, method, accessor, or property was expected. 

### ISSUE THREAD

**Issue by msoni11** [ingageco/capacitor-music-controls-plugin-for-capacitor-2#5]
I'm getting following error when I installed this plugin.
**[12:18:11]  typescript: src/shared/components/audio-book/audio-book.ts, line: 81 
            Unexpected token. A constructor, method, accessor, or property was expected.** 

      L80:      toastOpened:boolean = false;
      L81:      const { CapacitorMusicControls } = Plugins;

**Installed versions:**
"@capacitor/core": "^2.1.0",
"@capacitor/ios": "^2.1.0",
"@angular/core": "^8.2.14",
"@ionic-native/core": "^5.1.0",

**Comment by ingageco** [comment]
This error is unrelated to this plugin.

**Comment by ingageco** [comment]
The CapacitorMusicControls import should be at the top of your file, in your imports - not in your component class.

**Comment by msoni11** [comment]
Thank you @ingageco 

I was able to built it successfully but got this error in Xcode while running the app in iPhone 8 plus simulator.
```
Fatal error: Unexpectedly found nil while unwrapping an Optional value
at line 457: if(self.musicControlsInfo.hasSkipForward!){
```

**Comment by msoni11** [comment]
Never mind. It worked for me now. I need to support cover image value and hasSkipForward with my object in typescript. There are no longer optional and if we want, we need to deal it by considering latest swift terminology for optional values.

**Comment by ingageco** [comment]
@msoni11 No problem. There are a lot of updates to the plugin that will be pushed within the next week. I've updated from some of the forks, and iOS is working great. Android is the current focus and when i have that updated i'll be pushing to update the repo.
