### ISSUE TITLE
Error importing class into MainActivity

### ISSUE THREAD

**Issue by Bcamargoz** [ingageco/capacitor-music-controls-plugin-for-capacitor-2#6]
Hello good morning, I have been looking for this plugin for a while and I think this fork is excellent but while trying to implement it I have the following error Android Studio can't find com.ingageco package.

I have followed the instructions for Android implementation because there are only 2 steps to install the plugin with the command

`npm install capacitor-music-controls-plugin`

And then put the following code in the MainActivity,

` import com.ingageco.capacitormusiccontrols.CapacitorMusicControls;`
`add(CapacitorMusicControls.class);`

but can't find the package, could you help me with this error, it would be very helpful, thank you in advance.

**Comment by ingageco** [comment]
@Bcamargoz the add() part should be inside of your Bridge Activity block, not paired at the top with your import.

**Comment by Bcamargoz** [comment]
Yes, it really was an error with Android Studio and the synchronization, but now if I found a problem when trying to run the application I get the following error message

`...\capacitor-music-controls-plugin\android\src\main\java\com\ingageco\capacitormusiccontrols\CapacitorMusicControls.java:70: error: cannot access AppCompatActivity
		final Context context=getActivity().getApplicationContext();`

And on the console I can see the following message

`cannot access AppCompatActivity
class file for android.support.v7.app.AppCompatActivity not found`

Could you help me with this one, I would really appreciate it

**Comment by FloryanFilip** [comment]
```
import com.getcapacitor.BridgeActivity;
import com.ingageco.capacitormusiccontrols.CapacitorMusicControls;

public class MainActivity extends BridgeActivity {
 add(CapacitorMusicControls.class);
}

Am I doing something wrong? @ingageco

**Comment by alexanchek** [comment]
thank you for this! I don't understand how to add this too:

```
import com.getcapacitor.BridgeActivity;
import com.ingageco.capacitormusiccontrols.CapacitorMusicControls;

public class MainActivity extends BridgeActivity {
 add(CapacitorMusicControls.class);
}
```

please someone, show how to do this right way

**Comment by FloryanFilip** [comment]
so it actually should be:
```
import android.os.Bundle;
import com.getcapacitor.BridgeActivity;
import com.ingageco.capacitormusiccontrols.CapacitorMusicControls;

public class MainActivity extends BridgeActivity {
    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        registerPlugin(CapacitorMusicControls.class);
    }
}
```

**Comment by Oxey405** [comment]
Excuse me is @FloryanFilip right ? In that case, can an admin set the issue has resolved please ?

**Comment by ingageco** [comment]
Adding plugins to the MainActivity is well documented in the Capacitor 2 docs. Here is an example of implementing the plugin in your MainActivity. 

```
package com.mycompany.myapp;

import android.os.Bundle;

import com.getcapacitor.BridgeActivity;
import com.getcapacitor.Plugin;


import com.ingageco.capacitormusiccontrols.CapacitorMusicControls;
import java.util.ArrayList;

public class MainActivity extends BridgeActivity {
  @Override
  public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    // Initializes the Bridge
    this.init(savedInstanceState, new ArrayList<Class<? extends Plugin>>() {{
      // Additional plugins you've installed go here
      // Ex: add(TotallyAwesomePlugin.class);
      add(CapacitorMusicControls.class);
    }});
  }
}
```
