### ISSUE TITLE
Update track information

### ISSUE THREAD

**Issue by erixschueler** [ingageco/capacitor-music-controls-plugin-for-capacitor-2#7]
Hello,
I am looking for a way to update track information like album, artist, or title. Right now I recreate the music controls after initialization of a new track.  The creation animation is annoying and after recreation, the next button sometimes skips some tracks or recreates music controls in a loop.

You can update the controls play or pause button with the **updateIsPlaying** function. But I can not found any function which can update track, artist, album, or cover. 

Is there any function or possibility for updating these attributes or a solution to prevent this recreation bug?

**Comment by erixschueler** [comment]
Found an older answer from the parent plugin:

[https://github.com/homerours/cordova-music-controls-plugin/issues/82](https://github.com/homerours/cordova-music-controls-plugin/issues/82)

So this could solve my question.

**Comment by erixschueler** [comment]
Found a similar question in the parent plugin:

[https://github.com/homerours/cordova-music-controls-plugin/issues/82](https://github.com/homerours/cordova-music-controls-plugin/issues/82)

This answered my question.

**Comment by ingageco** [comment]
hey @erixschueler - im not sure that's a good solution in this instance. it's possible that you could end up creating multiple event listeners, with events firing multiple times - i can't say for sure at the moment. try it out and let me know if you see multiple events firing after changing the track info. 

in a future version we can add a simple track info update if needed.

**Comment by ingageco** [comment]
actually - that should work fine, at least on iOS. the event listener won't be recreated.

**Comment by B1Z1** [comment]
@ingageco Hey, i'm using your lib and I have the same problem. When I create new song, the song doesn't updates or removes existing, instead method "create" creates new object. Do you know how I can solve the problem? Method destroy doesn't work

**Comment by 313hemant313** [comment]
I did this to solve this.
In CapacitorMusicControls.java inside initialize method added this if condition.

`		if(null!=notification) {
			return;
		}
		notification = new MusicControlsNotification(activity, notificationID);`
