### ISSUE TITLE
Is the NPM repository up to date?

### ISSUE THREAD

**Issue by dansignia** [ingageco/capacitor-music-controls-plugin-for-capacitor-2#9]
I see there has been a recent commit that fixes an issue with a NullPointerException being thrown when calling destroy or create.

I have encountered this issue myself, and the fix that has been applied to the master branch does solve my problem.

When i install the plugin via NPM, it still seems to be using an older version of the plugin (0.9.2), and does not contain the latest changes from master.

Does the NPM package possibly need updating? or am i doing something incorrect.

**Comment by ingageco** [comment]
@dansignia Yes that's correct. I'll push an NPM update tonight or tomorrow!

**Comment by ingageco** [comment]
Updated
